### ISSUE TITLE
Invalid UCDs required

### ISSUE THREAD

**Issue by msdemlei** [ivoa-std/SSA#1]
SSAP requires the use of the UCD instr.fov, which is secondary only by
UCD; while this may be overly restrictive in the UCD list, I suppose
just moving to phys.angsize;instr.fov in SSAP wouldn't cause damage
either.

**Comment by loumir** [comment]
instr.fov represents a geometrical shape on the sky covered by an observing  instrument. 
Table columns should be specified unambiguously to designate what is measured or represented in the column value: 
phys.angSize;instr.fov  , phys.area;instr.fov ,  pos.outline;instr.fov

other SSAP UCD also for revision . see table attached 
[SSAP_appendixD_UCDCheckmL+Seb.pdf](https://github.com/ivoa-std/SSA/files/7129504/SSAP_appendixD_UCDCheckmL%2BSeb.pdf)

**Comment by msdemlei** [comment]
On Wed, Sep 08, 2021 at 07:18:54AM -0700, Mireille LOUYS wrote:
> instr.fov represents a geometrical shape on the sky covered by an
> observing  instrument.  Table columns should be specified
> unambiguously to designate what is measured or represented in the
> column value: phys.angSize;instr.fov  , phys.area;instr.fov ,
> pos.outline;instr.fov

While it may be a nice service to complete UCD assignment in a future
version of SSAP, I think for the present purpose (remove
contradictions between different IVOA specs), we should restrict
ourselves to the UCDs that actually conflict between SSAP and UCD and
fix those.  That's urgent in my book.  Anything else may be nice to
have in order to make SSAP responses more palatable to generic
clients.  But that, I claim, is a rather exotic use case, and anyway
it doesn't seem particularly urgent.

If you're sure you don't want to adapt UCD to SSAP usage, then it
seems the only way forward is to write an Erratum for SSAP, and that
necessarily needs to be restricted to the columns with the invalid
UCDs.

Who'll write this?  Should I?

**Comment by loumir** [comment]
I have updated the Errata pages for SSA_1.1. 

please check Errata 2 which  tackles instr.fov .

**Comment by msdemlei** [comment]
SSA 1.1 Erratum 2 approved by TCG on 2022-03-08.  Hence, this is fixed.
